cb: Enable Debugging builds, disable debugging mode for libvterm and MacOS CI
Disable debugging on MacOS CI, causes for some reasons it causes failure
like this:

```
clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -DDEBUG -Wall -Wshadow -Wmissing-prototypes   -DEXITFREE     -o objects/alloc.o alloc.c
make[1]: *** [objects/os_macosx.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from alloc.c:14:
./vim.h:533:11: fatal error: 'sodium.h' file not found
  533 | # include <sodium.h>
      |           ^~~~~~~~~~
1 error generated.
make[1]: *** [objects/alloc.o] Error 1
make: *** [first] Error 2
```

Signed-off-by: Christian Brabandt <cb@256bit.org>